name: Push to Pages

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy Markdown files
      run: |
        cp -r ./*.md ../wndgur2.github.io

    - name: Push changes to wndgur2.github.io
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.ACCESS_TOKEN }}
        branch: main 
        repository: wndgur2/wndgur2.github.io
        